### ISSUE TITLE
"Start Over" during X's turn makes O go twice

### ISSUE THREAD

**Issue by kybouw** [kybouw/TicTacToe#3]
During an AI game, clicking "Start Over" during your turn will rest the board and allow you to make the first turn in a new game. After you make your first turn, the AI will then take two turns, placing two O on the map instead of one.

**Comment by ImmutableBox** [comment]
If you aren't working on this problem I can try to have a look at it. 

I can't seem to recreate this bug. Clicking the "Start Over" button in an AI game and making your first move doesn't place two O on the map for me. Am I missing something?

**Comment by kybouw** [comment]
@ImmutableBox I guess that bug was in an older version or something. I cannot seem to reproduce it anymore, either. Thank you, anyway!
